# This file contains the recommended release configuration.
# This machine file is used to build release artifacts.
[built-in options]
buildtype = 'release'
wrap_mode = 'forcefallback'
default_library = 'static'

[zstd:built-in options]
lzma = 'disabled'
