name: Build cross Docker containers

on:
  push:
    paths:
      - alpine-docker/config-aarch64.mak
      - alpine-docker/config-arm.mak
      - alpine-docker/config-armhf.mak
      - alpine-docker/config-base.mak
      - alpine-docker/config-powerpc64le.mak
      - alpine-docker/config-riscv64.mak
      - alpine-docker/docker-bake.hcl
      - alpine-docker/save-versions.py
      - alpine-docker/universal.Dockerfile

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-24.04
    name: Build container

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    strategy:
      matrix:
        arch: [aarch64, arm, armhf, powerpc64le, riscv64]

    env:
      IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/musl-cross-make-alpine-${{ matrix.arch }}

    steps:
      - name: Set up Docker Buildx
        # v4.1.0
        # The hash below **must** be kept up-to-date with the 'Build and push' action
        # below.
        uses: docker/setup-buildx-action@d7f5e7f509e45cec5c76c4d5afdd7de93d0b3df5

      - name: Log in to the Container registry
        # v4.2.0
        # The hash below **must** be kept up-to-date with the 'Build and push' action
        # below.
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        # v6.1.0
        # The hash below **must** be kept up-to-date with the 'Build and push' action
        # below.
        uses: docker/metadata-action@80c7e94dd9b9319bd5eb7a0e0fe9291e23a2a2e9
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=raw,value={{date 'YYYY-MM-DD'}},enable={{is_default_branch}},priority=1000

      - uses: actions/checkout@v7

      - name: Build and push
        # v7.2.0
        # The hash below **must** be kept up-to-date with the 'Build and push' action
        # below.
        uses: docker/bake-action@6614cfa25eff9a0b2b2697efb0b6159e7680d584
        with:
          # The default git source pulls all submodules too, so use v6.8.0 instead.
          source: .
          workdir: alpine-docker
          files: |
            ./docker-bake.hcl
            cwd://${{ steps.meta.outputs.bake-file }}
          targets: ${{ matrix.arch }}
          # The hashes below **must** be kept up-to-date with the hashes above.
          set: |
            *.args.DOCKER_SETUP_BUILDX_ACTION_VERSION=d7f5e7f509e45cec5c76c4d5afdd7de93d0b3df5
            *.args.DOCKER_LOGIN_ACTION_VERSION=650006c6eb7dba73a995cc03b0b2d7f5ca915bee
            *.args.DOCKER_METADATA_ACTION_VERSION=80c7e94dd9b9319bd5eb7a0e0fe9291e23a2a2e9
            *.args.DOCKER_BAKE_ACTION_VERSION=6614cfa25eff9a0b2b2697efb0b6159e7680d584
          push: true

      # - name: Generate artifact attestation
      #   uses: actions/attest-build-provenance@v4
      #   with:
      #     subject-name: ${{ env.IMAGE_NAME }}
      #     # I don't know how to get the subject digest. See
      #     # https://github.com/docker/bake-action/issues/99
      #     subject-digest: 'sha256:fedcba0...'
      #     push-to-registry: true
