name: Build cross Docker containers

on:
  push:
    paths:
      - alpine-docker/config-aarch64.mak
      - alpine-docker/config-arm.mak
      - alpine-docker/config-armhf.mak
      - alpine-docker/config-base.mak
      - alpine-docker/config-powerpc64le.mak
      - alpine-docker/config-riscv64.mak
      - alpine-docker/docker-bake.hcl
      - alpine-docker/save-versions.py
      - alpine-docker/universal.Dockerfile

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-24.04
    name: Build container

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    strategy:
      matrix:
        arch: [aarch64, arm, armhf, powerpc64le, riscv64]

    env:
      IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/musl-cross-make-alpine-${{ matrix.arch }}

    steps:
      - name: Set up Docker Buildx
        # v3.11.1
        # The hash below **must** be kept up-to-date with the 'Build and push' action
        # below.
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435

      - name: Log in to the Container registry
        # v3.4.0
        # The hash below **must** be kept up-to-date with the 'Build and push' action
        # below.
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        # v5.7.0
        # The hash below **must** be kept up-to-date with the 'Build and push' action
        # below.
        uses: docker/metadata-action@902fa8ec7d6ecbf8d84d538b9b233a880e428804
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=raw,value={{date 'YYYY-MM-DD'}},enable={{is_default_branch}},priority=1000

      - uses: actions/checkout@v4

      - name: Build and push
        # v6.8.0
        # The hash below **must** be kept up-to-date with the 'Build and push' action
        # below.
        uses: docker/bake-action@37816e747588cb137173af99ab33873600c46ea8
        with:
          # The default git source pulls all submodules too, so use v6.8.0 instead.
          source: .
          workdir: alpine-docker
          files: |
            ./docker-bake.hcl
            cwd://${{ steps.meta.outputs.bake-file }}
          targets: ${{ matrix.arch }}
          # The hashes below **must** be kept up-to-date with the hashes above.
          set: |
            *.args.DOCKER_SETUP_BUILDX_ACTION_VERSION=e468171a9de216ec08956ac3ada2f0791b6bd435
            *.args.DOCKER_LOGIN_ACTION_VERSION=74a5d142397b4f367a81961eba4e8cd7edddf772
            *.args.DOCKER_METADATA_ACTION_VERSION=902fa8ec7d6ecbf8d84d538b9b233a880e428804
            *.args.DOCKER_BAKE_ACTION_VERSION=37816e747588cb137173af99ab33873600c46ea8
          push: true

      # - name: Generate artifact attestation
      #   uses: actions/attest-build-provenance@v2
      #   with:
      #     subject-name: ${{ env.IMAGE_NAME }}
      #     # I don't know how to get the subject digest. See
      #     # https://github.com/docker/bake-action/issues/99
      #     subject-digest: 'sha256:fedcba0...'
      #     push-to-registry: true
